version: "3.9"

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - server

  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile.server
    ports:
      - "8000:8000"
    volumes:
      - ../server:/app
    environment:
      - PYTHONUNBUFFERED=1
